import 'package:flutter/material.dart';
import 'package:fronto_rider/SharedWidgets/buttons.dart';
import 'package:fronto_rider/SharedWidgets/text.dart';

class TermsScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    double size = MediaQuery.of(context).size.height;
    String terms = 'License.\n\n'
        'Subject to your compliance with these Terms, Pronto grants you a limited, non-exclusive, non-sublicensable, revocable, non-transferable license to: (i) access and use the Applications on your personal device solely in connection with your use of the Services; and (ii) access and use any content, information and related materials that may be made available through the Services, in each case solely for your personal, noncommercial use. Any rights not expressly granted herein are reserved by Pronto and Pronto\'s licensors.\n'
        '\n\nRestrictions.\n\n'
        'You may not: (i) remove any copyright, trademark or other proprietary notices from any portion of the Services; (ii) reproduce, modify, prepare derivative works based upon, distribute, license, lease, sell, resell, transfer, publicly display, publicly perform, transmit, stream, broadcast or otherwise exploit the Services except as expressly permitted by Pronto; (iii) decompile, reverse engineer or disassemble the Services except as may be permitted by applicable law; (iv) link to, mirror or frame any portion of the Services; (v) cause or launch any programs or scripts for the purpose of scraping, indexing, surveying, or otherwise data mining any portion of the Services or unduly burdening or hindering the operation and/or functionality of any aspect of the Services; or (vi) attempt to gain unauthorized access to or impair any aspect of the Services or its related systems or networks.\n'
        '\n\nThird Party Services and Content.\n\n'
        'The Services may be made available or accessed in connection with third party services and content (including advertising) that Pronto does not control. You acknowledge that different terms of use and privacy policies may apply to your use of such third party services and content. Pronto does not endorse such third party services and content and in no event shall Pronto be responsible or liable for any products or services of such third party providers. Additionally, Apple Inc. and Google, Inc. will be a third-party beneficiary to this contract if you access the Services using Applications developed for Apple iOS, Android powered mobile devices, respectively. These third party beneficiaries are not parties to this contract and are not responsible for the provision or support of the Services in any manner. Your access to the Services using these devices is subject to terms set forth in the applicable third party beneficiary\'s terms of service.\n'
        '\n\n\n4. Access and Use of the Services\n\n'
        'User Accounts.\n\n'
        'In order to use most aspects of the Services, you must register for and maintain an active personal user Services account ("Account"). You must be at least 18 years of age, or the age of legal majority in your jurisdiction (if different than 18), to obtain an Account, unless a specific Service permits otherwise. Account registration requires you to submit to Pronto certain personal information, such as your name, address, mobile phone number, email address and age, as well as at least one valid payment method supported by Pronto. You agree to maintain accurate, complete, and up-to-date information in your Account. Your failure to maintain accurate, complete, and up-to-date Account information, including having an invalid or expired payment method on file, may result in your inability to access or use the Services. You are responsible for all activity that occurs under your Account, and you agree to maintain the security and secrecy of your Account username and password at all times. Unless otherwise permitted by Pronto in writing, you may only possess one Account.\n'
        '\n\n\nUser Requirements and Conduct.\n\n'
        'The Service is not available for use by persons under the age of 18. You may not authorize third parties to use your Account, and you may not allow persons under the age of 18 to receive transportation or logistics services from Third Party Providers unless they are accompanied by you. You may not assign or otherwise transfer your Account to any other person or entity. You agree to comply with all applicable laws when accessing or using the Services, and you may only access or use the Services for lawful purposes (e.g., no transport of unlawful or hazardous materials). You may not in your access or use of the Services cause nuisance, annoyance, inconvenience, or property damage, whether to the Third Party Provider or any other party. If you fail to comply with these Terms (including policies and supplemental terms), you may be denied access to or use of the Services and Pronto may charge you a cancellation fee for a transaction that could not be completed because of your failure to comply with these Terms. In certain instances you may be asked to provide proof of identity or other method of identity verification to access or use the Services, and you agree that you may be denied access to or use of the Services if you refuse to provide proof of identity or other method of identity verification.\n'
        '\n\n\nText Messaging and Telephone Calls.\n\n'
        'You agree that Pronto may contact you by telephone or text messages (including by an automatic telephone dialing system) at any of the phone numbers provided by you or on your behalf in connection with an Pronto account, including for marketing purposes. You understand that you are not required to provide this consent as a condition of purchasing any property, goods or services. You also understand that you may opt out of receiving text messages from Pronto at any time,by contacting info@pronto.com.ng If you do not choose to opt out, Pronto may contact you as outlined in its User Privacy Statement, located at https://www.pronto.com.ng/privacy/ notice\n'
        '\n\n\nUser Provided Content.\n\n'
        'Pronto may, in Pronto\'s sole discretion, permit you from time to time to submit, upload, publish or otherwise make available to Pronto through the Services textual, audio, and/or visual content and information, including commentary and feedback related to the Services, initiation of support requests, and submission of entries for competitions and promotions ("User Content"). Any User Content provided by you remains your property. However, by providing User Content to Pronto, you grant Pronto a worldwide, perpetual, irrevocable, transferable, royalty-free license, with the right to sublicense, to use, copy, modify, create derivative works of, distribute, publicly display, publicly perform, and otherwise exploit in any manner such User Content in all formats and distribution channels now known or hereafter devised (including in connection with the Services and Pronto\'s business and on third-party sites and services), without further notice to or consent from you, and without the requirement of payment to you or any other person or entity.\n'
        '\nYou represent and warrant that: (i) you either are the sole and exclusive owner of all User Content or you have all rights, licenses, consents and releases necessary to grant Pronto the license to the User Content as set forth above; and (ii) neither the User Content, nor your submission, uploading, publishing or otherwise making available of such User Content, nor Pronto\'s use of the User Content as permitted herein will infringe, misappropriate or violate a third party\'s intellectual property or proprietary rights, or rights of publicity or privacy, or result in the violation of any applicable law or regulation.\n'
        '\nYou agree to not provide User Content that is defamatory, libelous, hateful, violent, obscene, pornographic, unlawful, or otherwise offensive, as determined by Pronto in its sole discretion, whether or not such material may be protected by law. Pronto may, but shall not be obligated to, review, monitor, or remove User Content, at Pronto\'s sole discretion and at any time and for any reason, without notice to you.\n'
        '\n\n\nNetwork Access and Devices.\n\n'
        'You are responsible for obtaining the data network access necessary to use the Services. Your mobile network\'s data and messaging rates and fees may apply if you access or use the Services from your device. You are responsible for acquiring and updating compatible hardware or devices necessary to access and use the Services and Applications and any updates thereto. Pronto does not guarantee that the Services, or any portion thereof, will function on any particular hardware or devices. In addition, the Services may be subject to malfunctions and delays inherent in the use of the Internet and electronic communications.\n'
        '\n\n\n5. Payment\n\n'
        'You understand that use of the Services may result in charges to you for the services or goods you receive ("Charges"). Pronto will receive and/or enable your payment of the applicable Charges for services or goods obtained through your use of the Services. Charges will be inclusive of applicable taxes where required by law. Charges may include other applicable fees, tolls, and/or surcharges including a booking fee, municipal tolls, airport surcharges or processing fees for split payments. Please visit www.pronto.com.ng for further information on your particular location.\n'
        '\nAll Charges and payments will be enabled by Pronto using the preferred payment method designated in your Account, after which you will receive a receipt by email. If your primary Account payment method is determined to be expired, invalid or otherwise not able to be charged, you agree that Pronto may use a secondary payment method in your Account, if available. Charges paid by you are final and non-refundable, unless otherwise determined by Pronto.\n'
        '\nAs between you and Pronto, Pronto reserves the right to establish, remove and/or revise Charges for any or all services or goods obtained through the use of the Services at any time in Pronto\'s sole discretion. Further, you acknowledge and agree that Charges applicable in certain geographical areas may increase substantially during times of high demand. Pronto will use reasonable efforts to inform you of Charges that may apply, provided that you will be responsible for Charges incurred under your Account regardless of your awareness of such Charges or the amounts thereof. Pronto may from time to time provide certain users with promotional offers and discounts that may result in different amounts charged for the same or similar services or goods obtained through the use of the Services, and you agree that such promotional offers and discounts, unless also made available to you, shall have no bearing on your use of the Services or the Charges applied to you. You may elect to cancel your request for Services at any time prior to the commencement of such Services, in which case you may be charged a cancellation fee on a Third Party Provider’s behalf. After you have received services or goods obtained through the Service, you will have the opportunity to rate your experience and leave additional feedback. Pronto may use the proceeds of any Charges for any purpose, subject to any payment obligations it has agreed to with any Third Party Providers or other third parties.\n'
        '\nIn certain cases, with respect to Third Party Providers, Charges you incur will be owed directly to Third Party Providers, and Pronto will collect payment of those charges from you, on the Third Party Provider’s behalf as their limited payment collection agent, and payment of the Charges shall be considered the same as payment made directly by you to the Third Party Provider. In such cases, you retain the right to request lower Charges from a Third Party Provider for services or goods received by you from such Third Party Provider at the time you receive such services or goods, and Charges you incur will be owed to the Third Party Provider. Pronto will respond accordingly to any request from a Third Party Provider to modify the Charges for a particular service or good. This payment structure is intended to fully compensate a Third Party Provider, if applicable, for the services or goods obtained in connection with your use of the Services. In all other cases, Charges you incur will be owed and paid directly to Pronto or its affiliates, where Pronto is solely liable for any obligations to Third Party Providers. In such cases, you retain the right to request lower Charges from Pronto for services or goods received by you from a Third Party Provider at the time you receive such services or goods, and Pronto will respond accordingly to any request from you to modify the Charges for a particular service or good. Except with respect to taxicab transportation services requested through the Application, Pronto does not designate any portion of your payment as a tip or gratuity to a Third Party Provider. Any representation by Pronto (on Pronto\'s website, in the Application, or in Pronto\'s marketing materials) to the effect that tipping is "voluntary," "not required," and/or "included" in the payments you make for services or goods provided is not intended to suggest that Pronto provides any additional amounts, beyond those described above, to a Third Party Provider you may use. You understand and agree that, while you are free to provide additional payment as a gratuity to any Third Party Provider who provides you with services or goods obtained through the Service, you are under no obligation to do so. Gratuities are voluntary.\n'
        '\n\n\nRepair, Cleaning or Lost and Found Fees.\n\n'
        'You shall be responsible for the cost of repair for damage to, or necessary cleaning of, vehicles and property resulting from use of the Services under your Account in excess of normal "wear and tear" damages and necessary cleaning ("Repair or Cleaning"). In the event that a Repair or Cleaning request is verified by Pronto in Pronto\'s reasonable discretion, Pronto reserves the right to facilitate payment for the reasonable cost of such Repair or Cleaning using your payment method designated in your Account. Such amounts, as well as those pertaining to lost and found goods, will be transferred by Pronto to a Third Party Provider, if applicable, and are non-refundable.\n'
        '\n\n\nOwnership.\n\n'
        'The Services and all rights therein are and shall remain Pronto\'s property or the property of Pronto\'s licensors. Neither these Terms nor your use of the Services convey or grant to you any rights: (i) in or related to the Services except for the limited license granted above; or (ii) to use or reference in any manner Pronto\'s company names, logos, product and service names, trademarks or services marks or those of Pronto\'s licensors.\n'
        '\n\n\n6. Disclaimers; Limitation of Liability; Indemnity.\n\n'
        'DISCLAIMER.\n\n'
        'THE SERVICES ARE PROVIDED "AS IS" AND "AS AVAILABLE." PRONTO DISCLAIMS ALL REPRESENTATIONS AND WARRANTIES, EXPRESS, IMPLIED, OR STATUTORY, NOT EXPRESSLY SET OUT IN THESE TERMS, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN ADDITION, PRONTO MAKES NO REPRESENTATION, WARRANTY, OR GUARANTEE REGARDING THE RELIABILITY, TIMELINESS, QUALITY, SUITABILITY, OR AVAILABILITY OF THE SERVICES OR ANY SERVICES OR GOODS REQUESTED THROUGH THE USE OF THE SERVICES, OR THAT THE SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE. PRONTO DOES NOT GUARANTEE THE QUALITY, SUITABILITY, SAFETY OR ABILITY OF THIRD PARTY PROVIDERS. YOU AGREE THAT THE ENTIRE RISK ARISING OUT OF YOUR USE OF THE SERVICES, AND ANY SERVICE OR GOOD REQUESTED IN CONNECTION THEREWITH, REMAINS SOLELY WITH YOU, TO THE MAXIMUM EXTENT PERMITTED UNDER APPLICABLE LAW.\n'
        '\n\nLIMITATION OF LIABILITY.\n\n'
        'PRONTO SHALL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, PUNITIVE, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, LOST DATA, PERSONAL INJURY, OR PROPERTY DAMAGE RELATED TO, IN CONNECTION WITH, OR OTHERWISE RESULTING FROM ANY USE OF THE SERVICES, REGARDLESS OF THE NEGLIGENCE (EITHER ACTIVE, AFFIRMATIVE, SOLE, OR CONCURRENT) OF PRONTO, EVEN IF PRONTO HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.\n'
        '\nPRONTO SHALL NOT BE LIABLE FOR ANY DAMAGES, LIABILITY OR LOSSES ARISING OUT OF: (i) YOUR USE OF OR RELIANCE ON THE SERVICES OR YOUR INABILITY TO ACCESS OR USE THE SERVICES; OR (ii) ANY TRANSACTION OR RELATIONSHIP BETWEEN YOU AND ANY THIRD PARTY PROVIDER, EVEN IF PRONTO HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. PRONTO SHALL NOT BE LIABLE FOR DELAY OR FAILURE IN PERFORMANCE RESULTING FROM CAUSES BEYOND PRONTO\'S REASONABLE CONTROL. YOU ACKNOWLEDGE THAT THIRD PARTY PROVIDERS PROVIDING TRANSPORTATION SERVICES REQUESTED THROUGH SOME REQUEST PRODUCTS MAY OFFER RIDESHARING OR PEER-TO-PEER TRANSPORTATION SERVICES AND MAY NOT BE PROFESSIONALLY LICENSED OR PERMITTED.\n'
        '\nTHE SERVICES MAY BE USED BY YOU TO REQUEST AND SCHEDULE TRANSPORTATION, GOODS, OR LOGISTICS SERVICES WITH THIRD PARTY PROVIDERS, BUT YOU AGREE THAT PRONTO HAS NO RESPONSIBILITY OR LIABILITY TO YOU RELATED TO ANY TRANSPORTATION, GOODS OR LOGISTICS SERVICES PROVIDED TO YOU BY THIRD PARTY PROVIDERS OTHER THAN AS EXPRESSLY SET FORTH IN THESE TERMS.\n'
        '\nTHE LIMITATIONS AND DISCLAIMER IN THIS SECTION DO NOT PURPORT TO LIMIT LIABILITY OR ALTER YOUR RIGHTS AS A CONSUMER THAT CANNOT BE EXCLUDED UNDER APPLICABLE LAW. BECAUSE SOME STATES OR JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF OR THE LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, IN SUCH STATES OR JURISDICTIONS, PRONTO’S LIABILITY SHALL BE LIMITED TO THE EXTENT PERMITTED BY LAW. THIS PROVISION SHALL HAVE NO EFFECT ON PRONTO’S CHOICE OF LAW PROVISION SET FORTH BELOW.\n'
        '\n\n\nIndemnity.\n\n'
        'You agree to indemnify and hold Pronto and its affiliates and their officers, directors, employees, and agents harmless from any and all claims, demands, losses, liabilities, and expenses (including attorneys\' fees), arising out of or in connection with: (i) your use of the Services or services or goods obtained through your use of the Services; (ii) your breach or violation of any of these Terms; (iii) Pronto\'s use of your User Content; or (iv) your violation of the rights of any third party, including Third Party Providers.                                    ';
    return Scaffold(
      body: Stack(
        children: [
          Container(
            height: size,
            padding: EdgeInsets.only(left: 40, right: 40, top: size * 0.14),
            child: SingleChildScrollView(
              child: Column(
                children: [
                  buildTitlenSubtitleText(
                      terms, Colors.black87, 14, FontWeight.normal, null, null)
                ],
              ),
            ),
          ),
          getDrawerNavigator(
            context,
            size,
            'Terms',
          ),
        ],
      ),
    );
  }
}
